### PR TITLE
solution

### PR DESCRIPTION
**Pull request by Dmytrosp**
[DEMO LINK](https://Dmytrosp.github.io/react_list-of-goods-js/)

### CODE REVIEW

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Unfortunately, your project is not reachable via the demo link(

**Review by nazarmatsevych — CHANGES_REQUESTED** [review]
Demo link still not working :(

If you have any questions - feel free to ask them in fe_chat

**Comment by Dmytrosp** [comment]
> Demo link still not working :(
> 
> If you have any questions - feel free to ask them in fe_chat

**Comment by Dmytrosp** [comment]
https://Dmytrosp.github.io/react_list-of-goods-js/

**Review by etojeDenys — APPROVED** [review]
amazing

**Pull request closed without merging**
